/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package com.mycompany.giangvandat71dctt22;

import controllerGiangVanDat.SachControllerGiangVanDat;
import java.awt.Color;
import java.sql.Date;
import java.util.ArrayList;
import java.util.List;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import modelGiangVanDat.SachModelGiangVanDat;

/**
 *
 * @author Admin
 */
public class jpnTableSachGiangVanDat extends javax.swing.JPanel {

    public DefaultTableModel tableModel;
    private JFrame frame;
    private List<SachModelGiangVanDat> listSach = new ArrayList<SachModelGiangVanDat>();
    private SachControllerGiangVanDat sachController;
    int current = -1;
    /**
     * Creates new form jpnTableSachGiangVanDat
     */
    public jpnTableSachGiangVanDat() {
        initComponents();
        tableModel = (DefaultTableModel) jtbListSach.getModel();
        sachController = new SachControllerGiangVanDat();
        setColumnTable();
        getBook();
        jtbListSach.setComponentPopupMenu(jpmListSach);
    }

    public void getBook(){
        tableModel.setRowCount(0);
        if(this.listSach.size()>0)
            this.listSach.clear();
        this.listSach = this.sachController.getListSach();
        if(listSach.size() > 0){
            for(SachModelGiangVanDat list : listSach ){
                Object[] s = new Object[]{
                    list.getTenSach(), list.getTheLoai(), list.getNamXuatBan(), list.getNgayNhap(), list.getGiaTien()
                };
                tableModel.addRow(s);
            }
        }
    }
    
    public void setColumnTable(){
        tableModel.setColumnIdentifiers(new Object[]{
            "Tên sách", "Thể loại", "Năm xuất bản", "Ngày nhập", "Giá tiền"
        });
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jpmListSach = new javax.swing.JPopupMenu();
        jmSua = new javax.swing.JMenuItem();
        jmXoa = new javax.swing.JMenuItem();
        jPanel2 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jtbListSach = new javax.swing.JTable();
        jPanel1 = new javax.swing.JPanel();

        jmSua.setText("Sửa");
        jmSua.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmSuaActionPerformed(evt);
            }
        });
        jpmListSach.add(jmSua);

        jmXoa.setText("Xóa");
        jmXoa.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jmXoaActionPerformed(evt);
            }
        });
        jpmListSach.add(jmXoa);

        setPreferredSize(new java.awt.Dimension(900, 500));

        jPanel2.setBackground(new java.awt.Color(0, 102, 255));
        jPanel2.setPreferredSize(new java.awt.Dimension(900, 50));

        jLabel1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Nhập thông tin tên sách cần tìm: ");

        txtSearch.setText("Nhập thông tin cần tìm...");
        txtSearch.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtSearchFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                txtSearchFocusLost(evt);
            }
        });
        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtSearchKeyPressed(evt);
            }
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });

        jButton1.setBackground(new java.awt.Color(51, 51, 255));
        jButton1.setFont(new java.awt.Font("Segoe UI", 0, 14)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Thêm Sách");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(15, 15, 15)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 219, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 240, Short.MAX_VALUE)
                .addComponent(jButton1)
                .addGap(15, 15, 15))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(txtSearch, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton1))
                .addContainerGap(9, Short.MAX_VALUE))
        );

        jPanel4.setPreferredSize(new java.awt.Dimension(900, 350));
        jPanel4.setRequestFocusEnabled(false);

        jScrollPane1.setPreferredSize(new java.awt.Dimension(900, 350));

        jtbListSach.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        jtbListSach.setSelectionMode(javax.swing.ListSelectionModel.SINGLE_SELECTION);
        jtbListSach.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbListSachMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(jtbListSach);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        jPanel1.setPreferredSize(new java.awt.Dimension(900, 140));

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 900, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 140, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, 300, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtSearchFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchFocusGained
        // TODO add your handling code here:
        if(txtSearch.getText().equals("Nhập thông tin cần tìm...")){
            txtSearch.setText("");
            txtSearch.setForeground(new Color(0,0,0));
        }
    }//GEN-LAST:event_txtSearchFocusGained

    private void txtSearchFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtSearchFocusLost
        // TODO add your handling code here:
        if(txtSearch.getText().equals("")){
            txtSearch.setText("Nhập thông tin cần tìm...");
            txtSearch.setForeground(new Color(153,153,153));
        }
    }//GEN-LAST:event_txtSearchFocusLost

    private void jtbListSachMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbListSachMouseClicked
        // TODO add your handling code here:
        current = jtbListSach.getSelectedRow();
    }//GEN-LAST:event_jtbListSachMouseClicked

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        frame = new editSachGiangVanDat();
        frame.setLocationRelativeTo(null);
        frame.setResizable(false);
        frame.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jmSuaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmSuaActionPerformed
        // TODO add your handling code here:
        if(current!=-1){
            SachModelGiangVanDat item = this.listSach.get(current);
            int id = item.getId();
            String TenSach = item.getTenSach();
            String TheLoai = item.getTheLoai();
            Date NamXuatBan = item.getNamXuatBan();
            Date NgayNhap = item.getNgayNhap();
            int GiaTien = item.getGiaTien();
            frame = new editSachGiangVanDat(id,TenSach,TheLoai,NamXuatBan,NgayNhap,GiaTien);
            frame.setLocationRelativeTo(null);
            frame.setResizable(false);
            frame.setVisible(true);
        }
    }//GEN-LAST:event_jmSuaActionPerformed

    private void jmXoaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jmXoaActionPerformed
        // TODO add your handling code here:
        if(current!=-1){
            SachModelGiangVanDat item = this.listSach.get(current);
            int option = JOptionPane.showConfirmDialog(null, "Bạn có chắc chắn muốn sửa đổi chứ?", "Xác nhận", JOptionPane.YES_NO_OPTION);
            if (option == JOptionPane.YES_OPTION) {
                boolean check = sachController.deleteSach(item.getId());
                if(check){
                    getBook();
                    JOptionPane.showMessageDialog(null, "Đã xóa thành công!");
                }else{
                    JOptionPane.showMessageDialog(null, "Lỗi không mong muốn! Vui lòng thao tác lại");
                }
            }
        }
        else{
            JOptionPane.showMessageDialog(null, "Vui lòng chọn dữ liệu để thao tác!");
        }
    }//GEN-LAST:event_jmXoaActionPerformed

    private void txtSearchKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyPressed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_txtSearchKeyPressed

    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // TODO add your handling code here:
        tableModel.setRowCount(0);
        if(this.listSach.size()>0)
            this.listSach.clear();
        this.listSach = sachController.searchSach(txtSearch.getText());
        if(listSach.size() > 0){
            for(SachModelGiangVanDat list : listSach ){
                Object[] s = new Object[]{
                    list.getTenSach(), list.getTheLoai(), list.getNamXuatBan(), list.getNgayNhap(), list.getGiaTien()
                };
                tableModel.addRow(s);
            }
        }

    }//GEN-LAST:event_txtSearchKeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JMenuItem jmSua;
    private javax.swing.JMenuItem jmXoa;
    private javax.swing.JPopupMenu jpmListSach;
    private javax.swing.JTable jtbListSach;
    private javax.swing.JTextField txtSearch;
    // End of variables declaration//GEN-END:variables
}
